<?php
/**
 * m_addemployeeテーブル定義クラス
 *
 * @link       
 * @author     
 * @license    
 * @package    Simplan
 * @version    1.1.1
 * @create date 2023/12/6
 */

class   MAddemployeeBasicsObject
{
    var $table_name;            //テーブル名
    var $table_comment;         //テーブルコメント
    var $field_name;            //フィールド名配列
    var $field_type;            //フィールド タイプ配列　[フィールド名]
    var $field_type_size;       //フィールド サイズ
    var $field_type_key;        //フィールド キー
    var $field_null;            //必須入力配列

    /**
     * コンストラクタ
     *
     * @access  public
     * @return  none
    **/
    function MAddemployeeBasicsObject() {
        $this->table_name   = 'm_addemployee';
        $this->table_comment= 'add employee';

        $this->field_name   = array(
                   'f_employee_id',
                   'f_emp_id',
                   'f_name',
                   'f_aadhar_number',
                   'f_pan_number',
                   'f_passport',
                   'f_passport_alert',
                   'f_issue_date',
                   'f_expiry_date',
                   'f_gender',
                   'f_date_of_birth',
                   'f_age',
                   'f_blood_group',
                   'f_status',
                   'f_address1',
                   'f_address2',
                   'f_city',
                   'f_state',
                   'f_pincode',
                   'f_country',
                   'f_mobile_number',
                   'f_office_telephone_number',
                   'f_office_email',
                   'f_personal_mail',
                   'f_relation_name',
                   'f_relationship',
                   'f_occupation',
                   'f_address',
                   'f_phone_number',
                   'f_emp_status',
                   'f_category',
                   'f_job_title',
                   'f_join_date',
                   'f_relive_date',
                   'f_location',
                   'f_description',
                   'f_image',
                   'f_experience',
                   'f_education_ug',
                   'f_degree_ug',
                   'f_university_ug',
                   'f_education_pg',
                   'f_degree_pg',
                   'f_university_pg',
                   'f_additional_skill',
                   'f_language',
                   'f_others',
                   'f_jlpt',
                   'f_bank_name',
                   'f_bank_branch',
                   'f_acc_no',
                   'f_ifsc_code',
                   'f_del_flg',
                   'f_reg_account',
                   'f_reg_time',
                   'f_upd_account',
                   'f_upd_time',

                );

        $this->field_type   = array(
                   'f_employee_id' => 'int',
                   'f_emp_id' => 'varchar',
                   'f_name' => 'varchar',
                   'f_aadhar_number' => 'varchar',
                   'f_pan_number' => 'char',
                   'f_passport' => 'varchar',
                   'f_passport_alert' => 'int',
                   'f_issue_date' => 'date',
                   'f_expiry_date' => 'date',
                   'f_gender' => 'char',
                   'f_date_of_birth' => 'date',
                   'f_age' => 'int',
                   'f_blood_group' => 'char',
                   'f_status' => 'char',
                   'f_address1' => 'varchar',
                   'f_address2' => 'varchar',
                   'f_city' => 'varchar',
                   'f_state' => 'varchar',
                   'f_pincode' => 'int',
                   'f_country' => 'char',
                   'f_mobile_number' => 'varchar',
                   'f_office_telephone_number' => 'varchar',
                   'f_office_email' => 'varchar',
                   'f_personal_mail' => 'varchar',
                   'f_relation_name' => 'varchar',
                   'f_relationship' => 'varchar',
                   'f_occupation' => 'varchar',
                   'f_address' => 'text',
                   'f_phone_number' => 'varchar',
                   'f_emp_status' => 'int',
                   'f_category' => 'varchar',
                   'f_job_title' => 'varchar',
                   'f_join_date' => 'date',
                   'f_relive_date' => 'date',
                   'f_location' => 'text',
                   'f_description' => 'text',
                   'f_image' => 'varchar',
                   'f_experience' => 'text',
                   'f_education_ug' => 'varchar',
                   'f_degree_ug' => 'varchar',
                   'f_university_ug' => 'varchar',
                   'f_education_pg' => 'char',
                   'f_degree_pg' => 'varchar',
                   'f_university_pg' => 'varchar',
                   'f_additional_skill' => 'text',
                   'f_language' => 'varchar',
                   'f_others' => 'varchar',
                   'f_jlpt' => 'varchar',
                   'f_bank_name' => 'varchar',
                   'f_bank_branch' => 'varchar',
                   'f_acc_no' => 'varchar',
                   'f_ifsc_code' => 'varchar',
                   'f_del_flg' => 'char',
                   'f_reg_account' => 'varchar',
                   'f_reg_time' => 'datetime',
                   'f_upd_account' => 'varchar',
                   'f_upd_time' => 'datetime',

                );

        $this->field_type_size  = array(
                   'f_employee_id' => '8',
                   'f_emp_id' => '20',
                   'f_name' => '25',
                   'f_aadhar_number' => '12',
                   'f_pan_number' => '10',
                   'f_passport' => '10',
                   'f_passport_alert' => '1',
                   'f_issue_date' => 'date',
                   'f_expiry_date' => 'date',
                   'f_gender' => '1',
                   'f_date_of_birth' => 'date',
                   'f_age' => '5',
                   'f_blood_group' => '1',
                   'f_status' => '1',
                   'f_address1' => '250',
                   'f_address2' => '250',
                   'f_city' => '15',
                   'f_state' => '15',
                   'f_pincode' => '6',
                   'f_country' => '1',
                   'f_mobile_number' => '10',
                   'f_office_telephone_number' => '11',
                   'f_office_email' => '256',
                   'f_personal_mail' => '256',
                   'f_relation_name' => '25',
                   'f_relationship' => '25',
                   'f_occupation' => '30',
                   'f_address' => 'text',
                   'f_phone_number' => '10',
                   'f_emp_status' => '10',
                   'f_category' => '50',
                   'f_job_title' => '50',
                   'f_join_date' => 'date',
                   'f_relive_date' => 'date',
                   'f_location' => 'text',
                   'f_description' => 'text',
                   'f_image' => '255',
                   'f_experience' => 'text',
                   'f_education_ug' => '10',
                   'f_degree_ug' => '50',
                   'f_university_ug' => '100',
                   'f_education_pg' => '1',
                   'f_degree_pg' => '50',
                   'f_university_pg' => '50',
                   'f_additional_skill' => 'text',
                   'f_language' => '50',
                   'f_others' => '25',
                   'f_jlpt' => '25',
                   'f_bank_name' => '50',
                   'f_bank_branch' => '30',
                   'f_acc_no' => '30',
                   'f_ifsc_code' => '15',
                   'f_del_flg' => '1',
                   'f_reg_account' => '10',
                   'f_reg_time' => 'datetime',
                   'f_upd_account' => '10',
                   'f_upd_time' => 'datetime',

                );

        $this->field_type_key   = array(
                   'f_employee_id' => 'PRI',
                   'f_emp_id' => '',
                   'f_name' => '',
                   'f_aadhar_number' => '',
                   'f_pan_number' => '',
                   'f_passport' => '',
                   'f_passport_alert' => '',
                   'f_issue_date' => '',
                   'f_expiry_date' => '',
                   'f_gender' => '',
                   'f_date_of_birth' => '',
                   'f_age' => '',
                   'f_blood_group' => '',
                   'f_status' => '',
                   'f_address1' => '',
                   'f_address2' => '',
                   'f_city' => '',
                   'f_state' => '',
                   'f_pincode' => '',
                   'f_country' => '',
                   'f_mobile_number' => '',
                   'f_office_telephone_number' => '',
                   'f_office_email' => '',
                   'f_personal_mail' => '',
                   'f_relation_name' => '',
                   'f_relationship' => '',
                   'f_occupation' => '',
                   'f_address' => '',
                   'f_phone_number' => '',
                   'f_emp_status' => '',
                   'f_category' => '',
                   'f_job_title' => '',
                   'f_join_date' => '',
                   'f_relive_date' => '',
                   'f_location' => '',
                   'f_description' => '',
                   'f_image' => '',
                   'f_experience' => '',
                   'f_education_ug' => '',
                   'f_degree_ug' => '',
                   'f_university_ug' => '',
                   'f_education_pg' => '',
                   'f_degree_pg' => '',
                   'f_university_pg' => '',
                   'f_additional_skill' => '',
                   'f_language' => '',
                   'f_others' => '',
                   'f_jlpt' => '',
                   'f_bank_name' => '',
                   'f_bank_branch' => '',
                   'f_acc_no' => '',
                   'f_ifsc_code' => '',
                   'f_del_flg' => '',
                   'f_reg_account' => '',
                   'f_reg_time' => '',
                   'f_upd_account' => '',
                   'f_upd_time' => '',

                );

        $this->field_null   = array(
                   'f_employee_id' => 'NO',
                   'f_emp_id' => 'YES',
                   'f_name' => 'YES',
                   'f_aadhar_number' => 'YES',
                   'f_pan_number' => 'YES',
                   'f_passport' => 'YES',
                   'f_passport_alert' => 'YES',
                   'f_issue_date' => 'YES',
                   'f_expiry_date' => 'YES',
                   'f_gender' => 'YES',
                   'f_date_of_birth' => 'YES',
                   'f_age' => 'YES',
                   'f_blood_group' => 'YES',
                   'f_status' => 'YES',
                   'f_address1' => 'YES',
                   'f_address2' => 'YES',
                   'f_city' => 'YES',
                   'f_state' => 'YES',
                   'f_pincode' => 'YES',
                   'f_country' => 'YES',
                   'f_mobile_number' => 'YES',
                   'f_office_telephone_number' => 'YES',
                   'f_office_email' => 'YES',
                   'f_personal_mail' => 'YES',
                   'f_relation_name' => 'YES',
                   'f_relationship' => 'YES',
                   'f_occupation' => 'YES',
                   'f_address' => 'YES',
                   'f_phone_number' => 'YES',
                   'f_emp_status' => 'YES',
                   'f_category' => 'YES',
                   'f_job_title' => 'YES',
                   'f_join_date' => 'YES',
                   'f_relive_date' => 'YES',
                   'f_location' => 'YES',
                   'f_description' => 'YES',
                   'f_image' => 'NO',
                   'f_experience' => 'YES',
                   'f_education_ug' => 'YES',
                   'f_degree_ug' => 'YES',
                   'f_university_ug' => 'YES',
                   'f_education_pg' => 'YES',
                   'f_degree_pg' => 'YES',
                   'f_university_pg' => 'YES',
                   'f_additional_skill' => 'YES',
                   'f_language' => 'YES',
                   'f_others' => 'YES',
                   'f_jlpt' => 'YES',
                   'f_bank_name' => 'YES',
                   'f_bank_branch' => 'YES',
                   'f_acc_no' => 'YES',
                   'f_ifsc_code' => 'YES',
                   'f_del_flg' => 'NO',
                   'f_reg_account' => 'YES',
                   'f_reg_time' => 'YES',
                   'f_upd_account' => 'YES',
                   'f_upd_time' => 'YES',

                );

        $this->field_comment= array(
                   'f_employee_id' => 'Employee id',
                   'f_emp_id' => 'DEFAULT NULL',
                   'f_name' => 'Employee first name',
                   'f_aadhar_number' => 'Employee aadhar number',
                   'f_pan_number' => 'Employee pan number',
                   'f_passport' => 'Employee passport',
                   'f_passport_alert' => 'Passport alert',
                   'f_issue_date' => 'Employee passport issue date',
                   'f_expiry_date' => 'Employee passport expiry date',
                   'f_gender' => 'Employee gender',
                   'f_date_of_birth' => 'Employee date of birth',
                   'f_age' => 'Employee age',
                   'f_blood_group' => 'Employee blood group',
                   'f_status' => 'Employee status',
                   'f_address1' => 'Employee address1',
                   'f_address2' => 'Employee address2',
                   'f_city' => 'Employee city',
                   'f_state' => 'Employee pincode',
                   'f_pincode' => 'Employee country',
                   'f_country' => 'Employee country',
                   'f_mobile_number' => 'Employee mobile number',
                   'f_office_telephone_number' => 'Employee office telephone number',
                   'f_office_email' => 'Employee work email',
                   'f_personal_mail' => 'Employee other mail',
                   'f_relation_name' => 'Employee relation name',
                   'f_relationship' => 'Employee relationship',
                   'f_occupation' => 'Employee relation occupation',
                   'f_address' => 'Employee relation address',
                   'f_phone_number' => 'Employee relation phone number',
                   'f_emp_status' => 'Employee job status',
                   'f_category' => 'Employee job category',
                   'f_job_title' => 'Employee job title',
                   'f_join_date' => 'Employee joining date',
                   'f_relive_date' => 'Employee relive date',
                   'f_location' => 'Employee job location',
                   'f_description' => 'comment',
                   'f_image' => 'Photos',
                   'f_experience' => 'Employee work experience',
                   'f_education_ug' => 'Employee education',
                   'f_degree_ug' => 'Employee degree',
                   'f_university_ug' => 'Employee university',
                   'f_education_pg' => 'Employee education pg',
                   'f_degree_pg' => 'Employee degree pg',
                   'f_university_pg' => 'Employee university pg',
                   'f_additional_skill' => 'Employee additional skill',
                   'f_language' => 'Employee language',
                   'f_others' => 'Employee other language',
                   'f_jlpt' => 'Employee JLPT level',
                   'f_bank_name' => 'Bank name',
                   'f_bank_branch' => 'Banks branch',
                   'f_acc_no' => 'Employee bank account number',
                   'f_ifsc_code' => 'Employee IFSC code',
                   'f_del_flg' => 'Delete flag',
                   'f_reg_account' => 'Registrant',
                   'f_reg_time' => 'Registration date',
                   'f_upd_account' => 'Updated by',
                   'f_upd_time' => 'Update date',

                );

    }
    //--------------------------------------------------------------------------
}
//------------------------------------------------------------------------------

?>
