;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; system.ini
; システムに関する設定ファイル
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;
; BASE
;;;;;;;;;;;;;;;;;;;;
[BASE]
    ;; システム名
    system_name    = "powercis"
    ;; 初期アクセス、不正アクセス時のデフォルトプロセス
    default_process     = "index"
    default_cliprocess  = "default"

;;;;;;;;;;;;;;;;;;;;
; DB設定
;;;;;;;;;;;;;;;;;;;;
[DB]
    ;; DBタイプ ("none", "mysql")
    ;db_type   = "none"
    db_type     = "mysql"
    ;; DBサーバ名
    db_host     = "localhost"
    ;; DBポート番号
    db_port     = "3306"
    ;; DB名
    db_name      = "ems"
    ;; DBユーザ名
    db_user     = "root"
    ;; DBパスワード
    db_pass     = ""

; [DB]
;     ;; DBタイプ ("none", "mysql")
;     ;db_type   = "none"
;     db_type     = "mysql"
;     ;; DBサーバ名
;     db_host     = "localhost"
;     ;; DBポート番号
;     db_port     = "3306"
;     ;; DB名
;     db_name      = "sample"
;     ;; DBユーザ名
;     db_user     = "root"
;     ;; DBパスワード
;     db_pass     = "admin63"

;;;;;;;;;;;;;;;;;;;;
; ログ関係設定
;;;;;;;;;;;;;;;;;;;;
[LOG]
    ;;;;;;;;;;;;;;;;;;;;
    ;; 通常ログ
    ;; ログレベル（debug < info < warning < error）
    log_level       = "debug"
    ;; ログファイル名
    log_file_name   = "system.log"
    ;; ログファイルサイズ（Bytes）
    log_file_size   = 1024000
    ;; バックアップファイル数
    log_backup      = 50
    ;; ログの日付フォーマット
    log_format      = "Y/m/d H:i:s"

    ;;;;;;;;;;;;;;;;;;;;
    ;; エラーログ
    ;; エラーログファイル名
    err_log_file_name  = "error.log"
    ;; エラーログファイルサイズ（Bytes）
    err_log_file_size  = 1024000
    ;; エラーバックアップファイル数
    err_log_backup     = 50
    ;; エラーログの日付フォーマット
    err_log_format     = "Y/m/d H:i:s"

    ;;;;;;;;;;;;;;;;;;;;
    ;; CLIログ
    ;; ログレベル（debug < info < warning < error）
    cli_log_level       = "debug"
    ;; ログファイル名
    cli_log_file_name   = "cli.log"
    ;; ログファイルサイズ（Bytes）
    cli_log_file_size   = 1024000
    ;; バックアップファイル数
    cli_log_backup      = 50
    ;; ログの日付フォーマット
    cli_log_format      = "Y/m/d H:i:s"

;;;;;;;;;;;;;;;;;;;;
; MAIL
;;;;;;;;;;;;;;;;;;;;
[MAIL]

    ;;;;;;;;;;;;;;;;;;;;
    ;; SMTP設定
    ; 送信メールをSMTPを利用するかどうか (true or false)
    ; 利用する場合は MAIL_SMTP_ から始まる項目を設定すること
    ; シングルクォートは要らない
    ; [note] 一般配布時は実際使われている設定名を記入するのは危険 !!!!!
    ;        送信先・BCC宛てアドレスにおいて、存在しないアドレスの場合、
    ;        メールの送信が失敗するので注意。
    ;mail_smtp_is = Off
    mail_smtp_is = On
    ;; SMTP認証を行うか (On or Off :シングルクォートは要らない)
    mail_smtp_auth = On
    ;; SMTP認証を行う場合のSMTPサーバ名
    mail_smtp_host = "mail.threet.co.jp"
    ;; SMTP認証を行う場合のユーザ名
    ;mail_smtp_username = "username"
    mail_smtp_username = "t-kambe@threet.co.jp"
    ;; SMTP認証を行う場合のパスワード
    ;mail_smtp_password = "password"
    mail_smtp_password = "20471120"
    ;; SMTP認証を行う場合のSecure
    ;mail_smtp_secure = "tls"
    mail_smtp_secure = ""
    ;; SMTP認証を行う場合のポート
    ;mail_smtp_port = "25"
    mail_smtp_port = "25"

    ;;;;;;;;;;;;;;;;;;;;
    ;; 拒否設定
    ;; 特定のサーバーから特定のメールアドレスへの送信を防ぐための定義
    ;; いずれもカンマ区切りで定義すること
    ;; テスト中のメール送信制御
    mail_denied_server    = "192.,10.,128.,172."
    ;; 送信先拒否アドレス
    mail_denied_addr      = "webmaster"
    ;; エラーメッセージ
    mail_denied_err_msg   = "メール送信について、プロパティファイルが本番サーバー設定になっている可能性があります。確認してください。"


;;
; Local Variables:
; tab-width: 4
; End:
