;; process.properties
; index
index  = "listProcess"
; list
list   = "listProcess"
; new
new    = "newProcess"
; edit
edit   = "editProcess"
; del
del    = "delProcess"
; detail
detail    = "detailProcess"