[simplan_command_config]
;相対指定の場合はappディレクトリからのパスとする
    www_dir = "../../public_html"

;テスト用
[user_test]
    ;UserかAdminかmod以下のディレクトリ名で指定すること
    group       = "user"    ; user/admin/common etc
    
    ;主に利用するDBのテーブル名を記述する。使用しない場合は空文字とする
    table       = "m_member_info_item_list"
    
    ;プロセス名を指定する
    APP_NAME    = "Simplanテスト"
    
    ;生成するプロセス
    MakeProcess = "Index|List|New|Edit|Delete|Detail|Display"
    
    ;モードのタイプ設定
    ; User | Admin 等
    mod_type    = "User"
    
    ;app/mod以下の配置先
    mod_dir     = "user/test"
    
    ;public_html以下の配置先
;   直下に置く場合は.
    public_dir  = "."

;テスト用
[account]
    ;UserかAdminかmod以下のディレクトリ名で指定すること
    group       = "admin"   ; user/admin/common etc
    
    ;主に利用するDBのテーブル名を記述する。使用しない場合は空文字とする
    table       = "m_user"
    
    ;プロセス名を指定する
    APP_NAME    = "管理者情報"
    
    ;生成するプロセス
    MakeProcess = "Index|List|New|Edit|Delete"
    
    ;モードのタイプ設定
    ; User | Admin 等
    mod_type    = "Admin"
    
    ;app/mod以下の配置先
    mod_dir     = "admin/account"
    
    ;public_html以下の配置先
;   直下に置く場合は.
    public_dir  = "."

;テスト用
[inquiry]
    ;UserかAdminかmod以下のディレクトリ名で指定すること
    group       = "user"    ; user/admin/common etc
    
    ;主に利用するDBのテーブル名を記述する。使用しない場合は空文字とする
    table       = "t_inquiry"
    
    ;プロセス名を指定する
    APP_NAME    = "管理者情報"
    
    ;生成するプロセス
    MakeProcess = "Index|List|New|Edit|Delete"
    
    ;モードのタイプ設定
    ; user | admin 等
    mod_type    = "user"
    
    ;app/mod以下の配置先
    mod_dir     = "user/inquiry"
    
    ;public_html以下の配置先
;   直下に置く場合は.
    public_dir  = "."

[question]
    ;UserかAdminかmod以下のディレクトリ名で指定すること
    group       = "user"    ; user/admin/common etc
    
    ;主に利用するDBのテーブル名を記述する。使用しない場合は空文字とする
    table       = "t_inquiry"
    
    ;プロセス名を指定する
    APP_NAME    = "管理者情報"
    
    ;生成するプロセス
    MakeProcess = "Index|List|New|Edit|Delete"
    
    ;モードのタイプ設定
    ; user | admin 等
    mod_type    = "user"
    
    ;app/mod以下の配置先
    mod_dir     = "user/question"
    
    ;public_html以下の配置先
;   直下に置く場合は.
    public_dir  = "."
