;******************************************************************************;
; システムプロパティファイル
;******************************************************************************
;*** システム名 ***
; 使用するかどうか未定
SYSTEM_NAME             = "ウェブ戦略"

:*** DB設定 ***
DB_TYPE                 = "mysql"
DB_HOST                 = "localhost"
DB_PORT                 = 3306
DB_NAME                 = "WebStrategy"
DB_USER                 = "webstrategy"
DB_PASS                 = "webstrategy"

;*** 初期アクセス、不正アクセス時のデフォルトプロセス ***
DEFAULT_PROCESS         = "index"

;*** ログ関係設定 ***
LOG_LEVEL               = "debug"             ; ログレベル（debug < info < warning < error）
LOG_FILE_NAME           = "system.log"        ; ログファイル名
LOG_FILE_SIZE           = 1024000           ; ログファイルサイズ（Bytes）
LOG_BACKUP              = 5                 ; バックアップファイル数
LOG_FORMAT              = "Y/m/d H:i:s"       ; ログの日付フォーマット

ERR_LOG_FILE_NAME       = "error.log"         ; エラーログファイル名
ERR_LOG_FILE_SIZE       = 1024000           ; エラーログファイルサイズ（Bytes）
ERR_LOG_BACKUP          = 5                 ; エラーバックアップファイル数
ERR_LOG_FORMAT          = "Y/m/d H:i:s"       ; エラーログの日付フォーマット

;*** テスト中のメール送信制御 ***
; 特定のサーバーから特定のメールアドレスへの送信を防ぐための定義
; いずれもカンマ区切りで定義すること
MAIL_DENIED_SERVER      = 192.,10.,128.,172.
MAIL_DENIED_ADDR        = "webmaster"
MAIL_DENIED_ERR_MSG     = "メール送信について、プロパティファイルが本番サーバー設定になっている可能性があります。確認してください。"

Analize_URL             = "exam.threet.jp/ws" ; 解析JavaScriptの置き場所 
