; process.properties
; index                 = loginProcess              // ログイン処理
{foreach from=$process_list item="cur" name="current"}
{$cur.process_type|str_pad:24:" "}= "{$cmd.target}{$cur.process_Label}Process";	{$cur.process_name}
{/foreach}
